export enum Status {
    WAITING = "WAITING",
    PATIENT_CANCEL = "PATIENT_CANCEL",
    DOCTOR_CANCEL = "DOCTOR_CANCEL",
    EXPIRED = "EXPIRED",
    ACCEPTED = "ACCEPTED",
    FINISHED = "FINISHED",
  }